/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ChatSessionKeyRouteImport } from './routes/chat/$sessionKey'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as ApiPingRouteImport } from './routes/api/ping'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as AdminWorkflowsRouteImport } from './routes/admin/workflows'
import { Route as AdminWebhooksRouteImport } from './routes/admin/webhooks'
import { Route as AdminTokensRouteImport } from './routes/admin/tokens'
import { Route as AdminStatusRouteImport } from './routes/admin/status'
import { Route as AdminMetricsRouteImport } from './routes/admin/metrics'
import { Route as AdminMemoryRouteImport } from './routes/admin/memory'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminIdeasRouteImport } from './routes/admin/ideas'
import { Route as AdminFleetRouteImport } from './routes/admin/fleet'
import { Route as AdminCronRouteImport } from './routes/admin/cron'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminBrowserRouteImport } from './routes/admin/browser'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as ApiAdminWorkflowsRouteImport } from './routes/api/admin/workflows'
import { Route as ApiAdminWebhooksRouteImport } from './routes/api/admin/webhooks'
import { Route as ApiAdminTokensRouteImport } from './routes/api/admin/tokens'
import { Route as ApiAdminStatusRouteImport } from './routes/api/admin/status'
import { Route as ApiAdminMetricsRouteImport } from './routes/api/admin/metrics'
import { Route as ApiAdminMemoryRouteImport } from './routes/api/admin/memory'
import { Route as ApiAdminLogsRouteImport } from './routes/api/admin/logs'
import { Route as ApiAdminIdeasRouteImport } from './routes/api/admin/ideas'
import { Route as ApiAdminFleetRouteImport } from './routes/api/admin/fleet'
import { Route as ApiAdminCronRouteImport } from './routes/api/admin/cron'
import { Route as ApiAdminConfigRouteImport } from './routes/api/admin/config'
import { Route as ApiAdminBrowserRouteImport } from './routes/api/admin/browser'
import { Route as ApiAdminApprovalsRouteImport } from './routes/api/admin/approvals'
import { Route as ApiAdminActivityRouteImport } from './routes/api/admin/activity'
import { Route as ApiAdminIdeasSubmitRouteImport } from './routes/api/admin/ideas.submit'
import { Route as ApiAdminIdeasStatusRouteImport } from './routes/api/admin/ideas.status'
import { Route as ApiAdminIdeasChatRouteImport } from './routes/api/admin/ideas.chat'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ChatSessionKeyRoute = ChatSessionKeyRouteImport.update({
  id: '/chat/$sessionKey',
  path: '/chat/$sessionKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPingRoute = ApiPingRouteImport.update({
  id: '/api/ping',
  path: '/api/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkflowsRoute = AdminWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTokensRoute = AdminTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatusRoute = AdminStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMetricsRoute = AdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMemoryRoute = AdminMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIdeasRoute = AdminIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCronRoute = AdminCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrowserRoute = AdminBrowserRouteImport.update({
  id: '/browser',
  path: '/browser',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminWorkflowsRoute = ApiAdminWorkflowsRouteImport.update({
  id: '/api/admin/workflows',
  path: '/api/admin/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWebhooksRoute = ApiAdminWebhooksRouteImport.update({
  id: '/api/admin/webhooks',
  path: '/api/admin/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTokensRoute = ApiAdminTokensRouteImport.update({
  id: '/api/admin/tokens',
  path: '/api/admin/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatusRoute = ApiAdminStatusRouteImport.update({
  id: '/api/admin/status',
  path: '/api/admin/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMetricsRoute = ApiAdminMetricsRouteImport.update({
  id: '/api/admin/metrics',
  path: '/api/admin/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMemoryRoute = ApiAdminMemoryRouteImport.update({
  id: '/api/admin/memory',
  path: '/api/admin/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogsRoute = ApiAdminLogsRouteImport.update({
  id: '/api/admin/logs',
  path: '/api/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIdeasRoute = ApiAdminIdeasRouteImport.update({
  id: '/api/admin/ideas',
  path: '/api/admin/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFleetRoute = ApiAdminFleetRouteImport.update({
  id: '/api/admin/fleet',
  path: '/api/admin/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCronRoute = ApiAdminCronRouteImport.update({
  id: '/api/admin/cron',
  path: '/api/admin/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConfigRoute = ApiAdminConfigRouteImport.update({
  id: '/api/admin/config',
  path: '/api/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBrowserRoute = ApiAdminBrowserRouteImport.update({
  id: '/api/admin/browser',
  path: '/api/admin/browser',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApprovalsRoute = ApiAdminApprovalsRouteImport.update({
  id: '/api/admin/approvals',
  path: '/api/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminActivityRoute = ApiAdminActivityRouteImport.update({
  id: '/api/admin/activity',
  path: '/api/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIdeasSubmitRoute = ApiAdminIdeasSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ApiAdminIdeasRoute,
} as any)
const ApiAdminIdeasStatusRoute = ApiAdminIdeasStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiAdminIdeasRoute,
} as any)
const ApiAdminIdeasChatRoute = ApiAdminIdeasChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ApiAdminIdeasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/browser': typeof AdminBrowserRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cron': typeof AdminCronRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/ideas': typeof AdminIdeasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/status': typeof AdminStatusRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/activity': typeof ApiAdminActivityRoute
  '/api/admin/approvals': typeof ApiAdminApprovalsRoute
  '/api/admin/browser': typeof ApiAdminBrowserRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/cron': typeof ApiAdminCronRoute
  '/api/admin/fleet': typeof ApiAdminFleetRoute
  '/api/admin/ideas': typeof ApiAdminIdeasRouteWithChildren
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/memory': typeof ApiAdminMemoryRoute
  '/api/admin/metrics': typeof ApiAdminMetricsRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/admin/tokens': typeof ApiAdminTokensRoute
  '/api/admin/webhooks': typeof ApiAdminWebhooksRoute
  '/api/admin/workflows': typeof ApiAdminWorkflowsRoute
  '/api/admin/ideas/chat': typeof ApiAdminIdeasChatRoute
  '/api/admin/ideas/status': typeof ApiAdminIdeasStatusRoute
  '/api/admin/ideas/submit': typeof ApiAdminIdeasSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/browser': typeof AdminBrowserRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cron': typeof AdminCronRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/ideas': typeof AdminIdeasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/status': typeof AdminStatusRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/activity': typeof ApiAdminActivityRoute
  '/api/admin/approvals': typeof ApiAdminApprovalsRoute
  '/api/admin/browser': typeof ApiAdminBrowserRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/cron': typeof ApiAdminCronRoute
  '/api/admin/fleet': typeof ApiAdminFleetRoute
  '/api/admin/ideas': typeof ApiAdminIdeasRouteWithChildren
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/memory': typeof ApiAdminMemoryRoute
  '/api/admin/metrics': typeof ApiAdminMetricsRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/admin/tokens': typeof ApiAdminTokensRoute
  '/api/admin/webhooks': typeof ApiAdminWebhooksRoute
  '/api/admin/workflows': typeof ApiAdminWorkflowsRoute
  '/api/admin/ideas/chat': typeof ApiAdminIdeasChatRoute
  '/api/admin/ideas/status': typeof ApiAdminIdeasStatusRoute
  '/api/admin/ideas/submit': typeof ApiAdminIdeasSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/connect': typeof ConnectRoute
  '/new': typeof NewRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/browser': typeof AdminBrowserRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cron': typeof AdminCronRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/ideas': typeof AdminIdeasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/memory': typeof AdminMemoryRoute
  '/admin/metrics': typeof AdminMetricsRoute
  '/admin/status': typeof AdminStatusRoute
  '/admin/tokens': typeof AdminTokensRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workflows': typeof AdminWorkflowsRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/ping': typeof ApiPingRoute
  '/api/send': typeof ApiSendRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/stream': typeof ApiStreamRoute
  '/chat/$sessionKey': typeof ChatSessionKeyRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/activity': typeof ApiAdminActivityRoute
  '/api/admin/approvals': typeof ApiAdminApprovalsRoute
  '/api/admin/browser': typeof ApiAdminBrowserRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/cron': typeof ApiAdminCronRoute
  '/api/admin/fleet': typeof ApiAdminFleetRoute
  '/api/admin/ideas': typeof ApiAdminIdeasRouteWithChildren
  '/api/admin/logs': typeof ApiAdminLogsRoute
  '/api/admin/memory': typeof ApiAdminMemoryRoute
  '/api/admin/metrics': typeof ApiAdminMetricsRoute
  '/api/admin/status': typeof ApiAdminStatusRoute
  '/api/admin/tokens': typeof ApiAdminTokensRoute
  '/api/admin/webhooks': typeof ApiAdminWebhooksRoute
  '/api/admin/workflows': typeof ApiAdminWorkflowsRoute
  '/api/admin/ideas/chat': typeof ApiAdminIdeasChatRoute
  '/api/admin/ideas/status': typeof ApiAdminIdeasStatusRoute
  '/api/admin/ideas/submit': typeof ApiAdminIdeasSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/connect'
    | '/new'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/browser'
    | '/admin/config'
    | '/admin/cron'
    | '/admin/fleet'
    | '/admin/ideas'
    | '/admin/logs'
    | '/admin/memory'
    | '/admin/metrics'
    | '/admin/status'
    | '/admin/tokens'
    | '/admin/webhooks'
    | '/admin/workflows'
    | '/api/history'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/chat/$sessionKey'
    | '/admin/'
    | '/api/admin/activity'
    | '/api/admin/approvals'
    | '/api/admin/browser'
    | '/api/admin/config'
    | '/api/admin/cron'
    | '/api/admin/fleet'
    | '/api/admin/ideas'
    | '/api/admin/logs'
    | '/api/admin/memory'
    | '/api/admin/metrics'
    | '/api/admin/status'
    | '/api/admin/tokens'
    | '/api/admin/webhooks'
    | '/api/admin/workflows'
    | '/api/admin/ideas/chat'
    | '/api/admin/ideas/status'
    | '/api/admin/ideas/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/new'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/browser'
    | '/admin/config'
    | '/admin/cron'
    | '/admin/fleet'
    | '/admin/ideas'
    | '/admin/logs'
    | '/admin/memory'
    | '/admin/metrics'
    | '/admin/status'
    | '/admin/tokens'
    | '/admin/webhooks'
    | '/admin/workflows'
    | '/api/history'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/chat/$sessionKey'
    | '/admin'
    | '/api/admin/activity'
    | '/api/admin/approvals'
    | '/api/admin/browser'
    | '/api/admin/config'
    | '/api/admin/cron'
    | '/api/admin/fleet'
    | '/api/admin/ideas'
    | '/api/admin/logs'
    | '/api/admin/memory'
    | '/api/admin/metrics'
    | '/api/admin/status'
    | '/api/admin/tokens'
    | '/api/admin/webhooks'
    | '/api/admin/workflows'
    | '/api/admin/ideas/chat'
    | '/api/admin/ideas/status'
    | '/api/admin/ideas/submit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/connect'
    | '/new'
    | '/admin/activity'
    | '/admin/approvals'
    | '/admin/browser'
    | '/admin/config'
    | '/admin/cron'
    | '/admin/fleet'
    | '/admin/ideas'
    | '/admin/logs'
    | '/admin/memory'
    | '/admin/metrics'
    | '/admin/status'
    | '/admin/tokens'
    | '/admin/webhooks'
    | '/admin/workflows'
    | '/api/history'
    | '/api/ping'
    | '/api/send'
    | '/api/sessions'
    | '/api/stream'
    | '/chat/$sessionKey'
    | '/admin/'
    | '/api/admin/activity'
    | '/api/admin/approvals'
    | '/api/admin/browser'
    | '/api/admin/config'
    | '/api/admin/cron'
    | '/api/admin/fleet'
    | '/api/admin/ideas'
    | '/api/admin/logs'
    | '/api/admin/memory'
    | '/api/admin/metrics'
    | '/api/admin/status'
    | '/api/admin/tokens'
    | '/api/admin/webhooks'
    | '/api/admin/workflows'
    | '/api/admin/ideas/chat'
    | '/api/admin/ideas/status'
    | '/api/admin/ideas/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  NewRoute: typeof NewRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiPingRoute: typeof ApiPingRoute
  ApiSendRoute: typeof ApiSendRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ChatSessionKeyRoute: typeof ChatSessionKeyRoute
  ApiAdminActivityRoute: typeof ApiAdminActivityRoute
  ApiAdminApprovalsRoute: typeof ApiAdminApprovalsRoute
  ApiAdminBrowserRoute: typeof ApiAdminBrowserRoute
  ApiAdminConfigRoute: typeof ApiAdminConfigRoute
  ApiAdminCronRoute: typeof ApiAdminCronRoute
  ApiAdminFleetRoute: typeof ApiAdminFleetRoute
  ApiAdminIdeasRoute: typeof ApiAdminIdeasRouteWithChildren
  ApiAdminLogsRoute: typeof ApiAdminLogsRoute
  ApiAdminMemoryRoute: typeof ApiAdminMemoryRoute
  ApiAdminMetricsRoute: typeof ApiAdminMetricsRoute
  ApiAdminStatusRoute: typeof ApiAdminStatusRoute
  ApiAdminTokensRoute: typeof ApiAdminTokensRoute
  ApiAdminWebhooksRoute: typeof ApiAdminWebhooksRoute
  ApiAdminWorkflowsRoute: typeof ApiAdminWorkflowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/chat/$sessionKey': {
      id: '/chat/$sessionKey'
      path: '/chat/$sessionKey'
      fullPath: '/chat/$sessionKey'
      preLoaderRoute: typeof ChatSessionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ping': {
      id: '/api/ping'
      path: '/api/ping'
      fullPath: '/api/ping'
      preLoaderRoute: typeof ApiPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workflows': {
      id: '/admin/workflows'
      path: '/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AdminWorkflowsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tokens': {
      id: '/admin/tokens'
      path: '/tokens'
      fullPath: '/admin/tokens'
      preLoaderRoute: typeof AdminTokensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/status': {
      id: '/admin/status'
      path: '/status'
      fullPath: '/admin/status'
      preLoaderRoute: typeof AdminStatusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/metrics': {
      id: '/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AdminMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memory': {
      id: '/admin/memory'
      path: '/memory'
      fullPath: '/admin/memory'
      preLoaderRoute: typeof AdminMemoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ideas': {
      id: '/admin/ideas'
      path: '/ideas'
      fullPath: '/admin/ideas'
      preLoaderRoute: typeof AdminIdeasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cron': {
      id: '/admin/cron'
      path: '/cron'
      fullPath: '/admin/cron'
      preLoaderRoute: typeof AdminCronRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/browser': {
      id: '/admin/browser'
      path: '/browser'
      fullPath: '/admin/browser'
      preLoaderRoute: typeof AdminBrowserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/workflows': {
      id: '/api/admin/workflows'
      path: '/api/admin/workflows'
      fullPath: '/api/admin/workflows'
      preLoaderRoute: typeof ApiAdminWorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/webhooks': {
      id: '/api/admin/webhooks'
      path: '/api/admin/webhooks'
      fullPath: '/api/admin/webhooks'
      preLoaderRoute: typeof ApiAdminWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tokens': {
      id: '/api/admin/tokens'
      path: '/api/admin/tokens'
      fullPath: '/api/admin/tokens'
      preLoaderRoute: typeof ApiAdminTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/status': {
      id: '/api/admin/status'
      path: '/api/admin/status'
      fullPath: '/api/admin/status'
      preLoaderRoute: typeof ApiAdminStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/metrics': {
      id: '/api/admin/metrics'
      path: '/api/admin/metrics'
      fullPath: '/api/admin/metrics'
      preLoaderRoute: typeof ApiAdminMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/memory': {
      id: '/api/admin/memory'
      path: '/api/admin/memory'
      fullPath: '/api/admin/memory'
      preLoaderRoute: typeof ApiAdminMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logs': {
      id: '/api/admin/logs'
      path: '/api/admin/logs'
      fullPath: '/api/admin/logs'
      preLoaderRoute: typeof ApiAdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ideas': {
      id: '/api/admin/ideas'
      path: '/api/admin/ideas'
      fullPath: '/api/admin/ideas'
      preLoaderRoute: typeof ApiAdminIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/fleet': {
      id: '/api/admin/fleet'
      path: '/api/admin/fleet'
      fullPath: '/api/admin/fleet'
      preLoaderRoute: typeof ApiAdminFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/cron': {
      id: '/api/admin/cron'
      path: '/api/admin/cron'
      fullPath: '/api/admin/cron'
      preLoaderRoute: typeof ApiAdminCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/api/admin/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/browser': {
      id: '/api/admin/browser'
      path: '/api/admin/browser'
      fullPath: '/api/admin/browser'
      preLoaderRoute: typeof ApiAdminBrowserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/approvals': {
      id: '/api/admin/approvals'
      path: '/api/admin/approvals'
      fullPath: '/api/admin/approvals'
      preLoaderRoute: typeof ApiAdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/activity': {
      id: '/api/admin/activity'
      path: '/api/admin/activity'
      fullPath: '/api/admin/activity'
      preLoaderRoute: typeof ApiAdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/ideas/submit': {
      id: '/api/admin/ideas/submit'
      path: '/submit'
      fullPath: '/api/admin/ideas/submit'
      preLoaderRoute: typeof ApiAdminIdeasSubmitRouteImport
      parentRoute: typeof ApiAdminIdeasRoute
    }
    '/api/admin/ideas/status': {
      id: '/api/admin/ideas/status'
      path: '/status'
      fullPath: '/api/admin/ideas/status'
      preLoaderRoute: typeof ApiAdminIdeasStatusRouteImport
      parentRoute: typeof ApiAdminIdeasRoute
    }
    '/api/admin/ideas/chat': {
      id: '/api/admin/ideas/chat'
      path: '/chat'
      fullPath: '/api/admin/ideas/chat'
      preLoaderRoute: typeof ApiAdminIdeasChatRouteImport
      parentRoute: typeof ApiAdminIdeasRoute
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminBrowserRoute: typeof AdminBrowserRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminCronRoute: typeof AdminCronRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminIdeasRoute: typeof AdminIdeasRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMemoryRoute: typeof AdminMemoryRoute
  AdminMetricsRoute: typeof AdminMetricsRoute
  AdminStatusRoute: typeof AdminStatusRoute
  AdminTokensRoute: typeof AdminTokensRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminWorkflowsRoute: typeof AdminWorkflowsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminBrowserRoute: AdminBrowserRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminCronRoute: AdminCronRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminIdeasRoute: AdminIdeasRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMemoryRoute: AdminMemoryRoute,
  AdminMetricsRoute: AdminMetricsRoute,
  AdminStatusRoute: AdminStatusRoute,
  AdminTokensRoute: AdminTokensRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminWorkflowsRoute: AdminWorkflowsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiAdminIdeasRouteChildren {
  ApiAdminIdeasChatRoute: typeof ApiAdminIdeasChatRoute
  ApiAdminIdeasStatusRoute: typeof ApiAdminIdeasStatusRoute
  ApiAdminIdeasSubmitRoute: typeof ApiAdminIdeasSubmitRoute
}

const ApiAdminIdeasRouteChildren: ApiAdminIdeasRouteChildren = {
  ApiAdminIdeasChatRoute: ApiAdminIdeasChatRoute,
  ApiAdminIdeasStatusRoute: ApiAdminIdeasStatusRoute,
  ApiAdminIdeasSubmitRoute: ApiAdminIdeasSubmitRoute,
}

const ApiAdminIdeasRouteWithChildren = ApiAdminIdeasRoute._addFileChildren(
  ApiAdminIdeasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ConnectRoute: ConnectRoute,
  NewRoute: NewRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiPingRoute: ApiPingRoute,
  ApiSendRoute: ApiSendRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiStreamRoute: ApiStreamRoute,
  ChatSessionKeyRoute: ChatSessionKeyRoute,
  ApiAdminActivityRoute: ApiAdminActivityRoute,
  ApiAdminApprovalsRoute: ApiAdminApprovalsRoute,
  ApiAdminBrowserRoute: ApiAdminBrowserRoute,
  ApiAdminConfigRoute: ApiAdminConfigRoute,
  ApiAdminCronRoute: ApiAdminCronRoute,
  ApiAdminFleetRoute: ApiAdminFleetRoute,
  ApiAdminIdeasRoute: ApiAdminIdeasRouteWithChildren,
  ApiAdminLogsRoute: ApiAdminLogsRoute,
  ApiAdminMemoryRoute: ApiAdminMemoryRoute,
  ApiAdminMetricsRoute: ApiAdminMetricsRoute,
  ApiAdminStatusRoute: ApiAdminStatusRoute,
  ApiAdminTokensRoute: ApiAdminTokensRoute,
  ApiAdminWebhooksRoute: ApiAdminWebhooksRoute,
  ApiAdminWorkflowsRoute: ApiAdminWorkflowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
